# Generated by Django 5.0.3 on 2024-03-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="student_email",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="details",
            name="admission_number",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="details",
            name="phone_number",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="details",
            name="student_name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
