# Generated by Django 5.0.3 on 2024-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "details",
            "0002_details_student_email_alter_details_admission_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
