# Generated by Django 4.1.13 on 2024-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_details_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('student_id', models.CharField(blank=True, default='', max_length=20, null=True, unique=True)),
                ('year_of_study', models.IntegerField(blank=True, default='', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=300)),
                ('business_email', models.CharField(max_length=300)),
                ('user_ip', models.CharField(max_length=300)),
                ('country', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
