# Generated by Django 4.1.13 on 2024-08-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_studentuser_userinfo_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default='2', null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='year_of_study',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
