# Generated by Django 5.0.7 on 2024-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_delete_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='mode_of_learning',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='program_entrance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.IntegerField(blank=True, default='Unspecified', null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
