# Generated by Django 5.0.7 on 2024-08-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_studentuser_mode_of_learning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='profile_picture',
        ),
    ]
